# This is a basic workflow to help you get started with Actions

name: Progetto IS2 workflow

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master_2 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: macos
    steps:

    - name: checkout
      uses: actions/checkout@v2

#    - name: Cache install...
#      uses: actions/cache@v1
#      with:
#        path: ${ANDROID_HOME}
#        key: manfrediciro

    - name: Installo Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: build dell'apk e ricavo package name dall'apk per il monkey test
      run: |
        chmod u+x ./gradlew
        ./gradlew assembleDebug
        packagenameloc=$(${ANDROID_HOME}/build-tools/24.0.0/aapt dump badging app/build/outputs/apk/debug/app-debug.apk | grep package:\ name | awk -v FS="'" '/package: name=/{print $2}')
        echo "::set-env name=packagename::"$packagenameloc""

    - name: Install SDK
      uses: ciromanfredi/android-emulator-runner
      with:
        operation: install

    - name: Create emulator
      uses: ciromanfredi/android-emulator-runner
      with:
        operation: create

    - name: Launch emulator
      uses: ciromanfredi/android-emulator-runner
      with:
        operation: launch

#        script: |
#          ./gradlew connectedAndroidTest
#          ./gradlew lint
#          adb -s emulator-5554 install app/build/outputs/apk/debug/app-debug.apk
#          adb shell monkey -p $packagename -v 100
#          chmod u+x .github/scripts/funesdroid.sh
#          .github/scripts/funesdroid.sh

    - name: Creo cartella per risultati Instrumented Test
      run: |
        mkdir -p risultatiIstruInstrumentedTest
        cp -R app/build/reports/androidTests/connected/ risultatiIstruInstrumentedTest/reports
        cp -R app/build/outputs/androidTest-results/connected/ risultatiIstruInstrumentedTest/outputs

    - name: Risultati Instrumented Test
      uses: actions/upload-artifact@v1
      with:
        name: Risultati Instrumented Test
        path: risultatiIstruInstrumentedTest

    - name: Creo cartella per risultati Lint Test
      run: |
        mkdir -p risultatiLintTest
        cp -R app/build/reports/lint-results.html risultatiLintTest
        cp -R app/build/reports/lint-results.xml risultatiLintTest

    - name: Risultati Lint Test
      uses: actions/upload-artifact@v1
      with:
        name: Risultati Lint Test
        path: risultatiLintTest

    - name: Risultati FunesDroid
      uses: actions/upload-artifact@v1
      with:
        name: Risultati FunesDroid
        path: FunesDroid-master/Results